Implement result event listener
ie3-institute/OSMoGrid pull request #116
Opened 2021-12-26 22:38 UTC by johanneshiry

Resolves #74

2022-01-25 09:36 UTC, t-ober submitted a review, later dismissed
This is just a quick partial review mainly of the `PersistenceResultListener`and the `ResultCsvSink`as the rest is bound to change according to the adapted `OsmoGridGuardian` changes

2022-01-25 09:36 UTC, t-ober commented on src/main/scala/edu/ie3/osmogrid/io/output/PersistenceResultListener.scala
> +              throw exception
reminder to update error handling and coordinated shutdown

2022-01-25 09:36 UTC, t-ober commented on src/main/scala/edu/ie3/osmogrid/io/output/PersistenceResultListener.scala
> +  private sealed trait ResultEvent
reminder to rethink naming

2022-01-25 09:36 UTC, t-ober commented on src/main/scala/edu/ie3/osmogrid/io/output/ResultCsvSink.scala
> +    else new EntityPersistenceNamingStrategy(),
```suggestion
    if (hierarchic)
      new FileNamingStrategy(
        new EntityPersistenceNamingStrategy(),
        new DefaultDirectoryHierarchy(runId.toString, runId.toString)
      )
    else new FileNamingStrategy(),
```

2022-01-25 09:36 UTC, t-ober commented on src/main/scala/edu/ie3/osmogrid/io/output/ResultCsvSink.scala
> +    else new EntityPersistenceNamingStrategy(),
also take care of imports

2023-07-11 09:25 UTC, danielfeismann requested changes
Just some minor things and questions

2023-07-19 12:25 UTC, julianhohmann commented on src/main/scala/edu/ie3/osmogrid/io/input/package.scala
> +      transformerTypes: Seq[Transformer2WTypeInput]
This class has not been changed, it was just moved to a separate file. Maybe we should create a new issue on that?

2023-07-19 14:46 UTC, julianhohmann commented on src/main/scala/edu/ie3/osmogrid/io/input/package.scala
> +      transformerTypes: Seq[Transformer2WTypeInput]
We have decided together to not consider 3WTransformers in OSMoGrid.

2023-07-26 08:41 UTC, julianhohmann commented on src/test/scala/edu/ie3/osmogrid/guardian/run/RunGuardianSpec.scala
> -
Deleted tests are restored.

2023-08-23 10:56 UTC, danielfeismann reviewed
Looks good to me. There are some conflicts and Jenkins is atm down. If both is fixed we should be ready to go here

2023-09-20 13:03 UTC, danielfeismann approved these changes
LGTM, thanks for the work done here!

2023-09-20 13:06 UTC, merged