To/#202 grid building
ie3-institute/OSMoGrid pull request #212
Opened 2022-07-06 07:43 UTC by t-ober

Resolves #202

2022-08-08 16:55 UTC, t-ober commented
There are some files here due to corrupt merge that are already in main but renamed. Reminder to self to check and delete the corresponding files from this PR

2023-06-27 22:55 UTC, julianhohmann requested changes
Great implementation of the LV grid generation. Thanks for your work! Just some minor issues and questions.

2023-06-27 22:55 UTC, julianhohmann commented on src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorIT.scala
> +        )
```suggestion
        messages.foreach(
          _.lvCoordinatorRegionCoordinatorAdapter shouldBe regionCoordinatorReply.ref
        )
        messages.foreach(
          _.lvCoordinatorGridGeneratorAdapter shouldBe gridGeneratorReply.ref
        )
```

2023-06-27 22:55 UTC, julianhohmann commented on src/test/scala/edu/ie3/osmogrid/lv/region_coordinator/LvRegionCoordinatorIT.scala
How can this test not fail? We are not using any MunicipalityCoordinator.

2023-06-27 22:55 UTC, julianhohmann commented on src/test/scala/edu/ie3/osmogrid/model/OsmoGridModelSpec.scala
> +        fail("Collection sholudn't be empty")
```suggestion
        fail("Collection shouldn't be empty")
```

2023-08-14 10:57 UTC, merged