Fixing some small bugs.
ie3-institute/OSMoGrid pull request #406
Opened 2024-04-15 12:07 UTC by staudtMarius

Resolves #405

2024-04-17 18:32 UTC, staudtMarius commented
Found some more bugs. There is still one issue. After that one is resolved, OSMoGrid can generate valid lv and mv grids.

2024-04-24 07:23 UTC, danielfeismann reviewed
I only briefly checked this. Good work! some very minor suggestions from my side.

2024-04-24 07:23 UTC, danielfeismann commented on src/test/scala/edu/ie3/test/common/GridSupport.scala
> +      s"Dummy A node in $subgridNo",
```suggestion
      s"Dummy nodeA in $subgridNo",
```

2024-04-24 07:23 UTC, danielfeismann commented on src/test/scala/edu/ie3/test/common/GridSupport.scala
> +      s"Dummy B1 node in $subgridNo",
```suggestion
      s"Dummy nodeB1 in $subgridNo",
```

2024-04-24 07:23 UTC, danielfeismann commented on src/test/scala/edu/ie3/test/common/GridSupport.scala
> +      s"Dummy B2 node in $subgridNo",
```suggestion
      s"Dummy nodeB2 in $subgridNo",
```

2024-04-24 07:23 UTC, danielfeismann commented on src/main/scala/edu/ie3/osmogrid/guardian/run/RunGuardian.scala
> +      // save sub grids if the should be put out
```suggestion
      // store sub grids if they should be put out
```

2024-04-24 16:33 UTC, danielfeismann requested changes
Almost there, should be the last issues from my side.

2024-04-24 16:33 UTC, danielfeismann commented on src/main/scala/edu/ie3/osmogrid/guardian/run/SubGridHandling.scala
> +  private def assignSubNetNumbers(
I opt to change this method name since there is already one method assignSubNetNumbers doing other things.

2024-04-24 16:33 UTC, danielfeismann commented on src/main/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSupport.scala
> +  /** Method for clustering lv grids.
Great, that you enhance the ScalaDocs as well!

2024-04-25 10:32 UTC, danielfeismann approved these changes
Great, that you fixed these bugs. Thanks!

2024-04-25 10:32 UTC, merged