Preventing unconnected nodes or subgrids.
ie3-institute/OSMoGrid pull request #429
Opened 2024-05-08 15:52 UTC by staudtMarius

Resolves #415

2024-05-16 07:55 UTC, staudtMarius commented
!test

2024-05-17 06:43 UTC, danielfeismann reviewed
Need to have a deeper look here later

2024-05-17 06:43 UTC, danielfeismann commented on src/main/scala/utils/Clustering.scala
> +  private def totalDistance(list: Set[Cluster]): Double = {
Please try if you find a naming that comply with sonar although it was named like this before.

2024-05-17 06:43 UTC, danielfeismann commented on src/main/scala/utils/Clustering.scala
> +  def run(implicit maxIteration: Int = 50): List[Cluster] = {
What are the reasons to increase the number of maxIterations?

2024-05-21 10:11 UTC, danielfeismann requested changes
Beside of two minor things this looks good to me

2024-05-21 10:11 UTC, danielfeismann commented on src/main/scala/edu/ie3/osmogrid/lv/LvGridGeneratorSupport.scala
> +    * removed if its degree is < 2 and it is not defined to be kept.
```suggestion
    * removed if its degree is <= 2 and it is not defined to be kept.
```

2024-05-21 10:55 UTC, danielfeismann approved these changes
LGTM!

2024-05-21 10:55 UTC, merged