Document legacy code in activity diagrams
ie3-institute/OSMoGrid pull request #86
Opened 2021-11-28 12:52 UTC by ckittl

Resolves #72

2021-11-28 12:56 UTC, johanneshiry commented
Does it make sense to add RTD support directly in the context of this PR? Would appreciate to have a consist documentation which (for now) also includes the legacy stuff, as it is then part of the documentation that will be available in the future and can be easily trace back :-)

2021-11-28 12:59 UTC, ckittl commented
:thinking: Wanted to introduce it with #75, but can do it here as well.

2021-11-28 13:43 UTC, ckittl commented
!test

2021-11-28 13:46 UTC, ckittl commented
Better, @johanneshiry ?

2021-11-29 12:50 UTC, t-ober requested changes

2021-11-29 12:50 UTC, t-ober commented on docs/readthedocs/conf.py
> +]
```suggestion
extensions = [
    'myst_parser',
    'sphinx.ext.autosectionlabel',
]
```

2021-11-29 12:50 UTC, t-ober commented on docs/readthedocs/conf.py
> +]
as recommonmark is deprecated (https://github.com/readthedocs/recommonmark)

2021-11-29 13:11 UTC, t-ober approved these changes

2021-11-29 13:11 UTC, merged